deploy:
  host: 0.0.0.0
  port: 5000
  log_level: info
  workers: 8

info:
  version: 1.0.0 (SNAPSHOT)
  maintainer: Henry Jaimes <henry512apk@gmail.com>

database:
  connection: postgresql+asyncpg://postgres:4N45Ep8NTrq@ec2-18-229-245-105.sa-east-1.compute.amazonaws.com/postgres
open_api:
  google_books:
    base_url: https://www.googleapis.com/books/v1/volumes
  open_libra:
    base_url: https://www.etnassoft.com/api/v1/get
