database:
  connection: postgresql+asyncpg://postgres:root@localhost/postgres
open_api:
  google_books:
    base_url: https://www.googleapis.com/books/v1/volumes
  open_libra:
    base_url: https://www.etnassoft.com/api/v1/get