database:
  connection: postgresql://postgres:root@localhost/postgres
  schema: public
  tables:
    books: books
    authors: authors
    categories: categories
    publishing: publishing
    books_authors: books_authors
    books_categories: books_categories
open_api:
  google_books:
    base_url: https://www.googleapis.com/books/v1/volumes
  open_libra:
    base_url: https://www.etnassoft.com/api/v1/get