version: "3.9"

services:
   api:
      image: api-books:latest
      restart: always
      ports:
          - 5000:5000
      networks:
          - group-r5
   database:
      image: postgres:14.1
      restart: always
      ports:
          - 5432:5432
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=4N45Ep8NTrq
          - POSTGRES_DB=postgres 
      networks:
          - group-r5


networks:
    group-r5:
